
server:
  port: 9000
spring:
  kafka:
    listerner:
      ack-mode: MANUAL_IMMEDIATE
    consumer:
      enable-auto-commit: false
      bootstrap-servers: 10.118.1.14:19092
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 10.118.1.14:19092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer